name: Create File on Main

on:
  pull_request:
    types:
      - closed

jobs:
  create_file:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add text to test.txt
      run: echo "auto added" >> test.txt

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add test.txt
        git commit -m "Add a new file and update .gitignore [skip ci]"
        git push
