name: Create File on Main

on:
  pull_request:
    types:
      - closed

jobs:
  create_file:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
    - name: Create the file
      run: echo "This is a file created by GitHub Actions." > my_created_file.txt

    - name: Add the file to .gitignore
      run: echo "my_created_file.txt" >> .gitignore

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add my_created_file.txt .gitignore
        git commit -m "Add a new file and update .gitignore [skip ci]"
